version: "3"

services:
  _base: &base
    image: gradle:8.0-jdk11-alpine
    env_file:
      - .env
    volumes:
      - .:/app
      - /tmp/.gradle:/home/gradle/.gradle
    working_dir: /app
    command: gradle bootRun

  dev:
    <<: *base
    ports:
      - "8080:8080"
    command: gradle bootRun

  build:
    <<: *base
    command: gradle test

  app:
    image: gradle:7-jdk11
    env_file:
      - .env
    environment:
      JAEGER_ENDPOINT: 'http://jaeger:14250'
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.ivy2:/root/.ivy2
      - gradle_cache:/home/gradle/.gradle
    working_dir: /app
    command: gradle bootRun
    hostname: app
    depends_on:
      - jaeger-all-in-one
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
#      - "14268:14268"
#      - "14250:14250"
#      - "9411:9411"

  # Collector
  otel-collector:
    image:  otel/opentelemetry-collector:0.77.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    hostname: otel-collector
    depends_on:
      - jaeger-all-in-one
      - prometheus

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    container_name: grafana

  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8888:8080"

volumes:
  gradle_cache: {}
