global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
#  - job_name: 'demo'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['app:8081']
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
