---
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services:
name: build
on:
  push:
    branches: [master]
jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    env:
      BUILD_ID: ${{github.run_number}}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::160071257600:role/github-action-role-ffeeae1
          aws-region: ap-northeast-1
          role-session-name: githubAction

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: moby-engine moby-cli docker-compose awscli
          version: 1.0

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.gradle/caches
            /tmp/.gradle/wrapper
          key: ${{ runner.os }}-gradle
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./auto/test

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: 'publish'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: ./auto/publish

      - name: 'eks login'
        run:  aws eks --region ap-northeast-1 update-kubeconfig --name noneprod-devkit-cluster

      - name: release
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: ./auto/deploy
